# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['schoolphotoID/main.py'],
    pathex=['D:/dev/SchoolFacerecognition', 'D:/dev/SchoolFacerecognition/src'],
    binaries=[],
    datas=[('app.ico', '.'), ('models', 'models')],
    hiddenimports=[
        'face_recognition',
        'face_recognition_models',
        'dlib',
        'dlib-bin',
        'numpy',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'schoolphotoID',
        'schoolphotoID.gui',
        'schoolphotoID.gui.worker',
        'schoolphotoID.gui.main_window',
        'schoolphotoID.core',
        'schoolphotoID.core.file_util',
        'src',
        'src.face_recognition_tool',
        'src.setup_face_recognition',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SchoolPhotoID',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='app.ico',
)